repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --no-cache]
        exclude: "\\.ipynb$"
      - id: ruff-format
        args: [--no-cache]
        exclude: "\\.ipynb$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: "\\.ipynb$"
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
